### ISSUE TITLE
visualization 

### ISSUE THREAD

**Issue by Amithomas** [starcolon/vor-knowledge-graph#7]
Is the visualization part working?

**Comment by starcolon** [comment]
yes it is. have you checked if your orientdb is populated with data properly? you can quickly see the sample of how to query the populated graph data in `visualise.js` (try querying in orientdb ui)

**Comment by starcolon** [comment]
btw, it's worth checking another branch out here https://github.com/starcolon/vor-knowledge-graph/tree/feature/content-segmentation the master is 1yr old and it's kinda old.

**Comment by Amithomas** [comment]
I was getting this error while running visualise.js
var [nodes, edges] = p;
            ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
Thats the reson why I asked

**Comment by starcolon** [comment]
which version of node.js are you running? i'm pretty sure you're likely on older versions of node which don't fully support ECMA6. 

suggested version: v9.3.0 or newer
